Testes de unidade dos services
atiliosilfer/afj-final-tp pull request #12
Opened 2024-09-02 01:41 UTC by felipebarroso

Parte dos testes de unidade das classes services.

2024-09-02 23:00 UTC, Lucas-Angelo requested changes

2024-09-02 23:00 UTC, Lucas-Angelo commented on user-ms/src/test/kotlin/puc/service/CustomUserDetailsServiceImplTest.kt
Essa classe de teste deveria estar no diretório `user-ms/src/test/kotlin/puc/service/impl`

2024-09-02 23:00 UTC, Lucas-Angelo commented on user-ms/src/test/kotlin/puc/service/UserAppServiceImplTest.kt
Essa classe de teste deveria estar no diretório `user-ms/src/test/kotlin/puc/service/impl`

2024-09-02 23:00 UTC, Lucas-Angelo commented
Faltam testar os métodos:

- `refreshToken`
- `updateUser`
- `changePassword`

2024-09-03 01:13 UTC, felipebarroso commented on user-ms/src/test/kotlin/puc/service/CustomUserDetailsServiceImplTest.kt
classe movida para pacote impl.

2024-09-03 01:13 UTC, felipebarroso commented on user-ms/src/test/kotlin/puc/service/UserAppServiceImplTest.kt
classe movida para pacote impl.

2024-09-03 01:15 UTC, felipebarroso commented
Adicionado testes para todos os métodos da classe UserAppServiceImpl.

2024-09-03 01:41 UTC, Lucas-Angelo requested changes

2024-09-03 01:41 UTC, Lucas-Angelo commented on user-ms/src/test/kotlin/puc/service/impl/UserAppServiceImplTest.kt
> +import puc.exception.custom.*
remover wildcard import

2024-09-03 01:41 UTC, Lucas-Angelo commented on user-ms/src/test/kotlin/puc/service/impl/UserAppServiceImplTest.kt
> +import java.util.*
remover wildcard import

2024-09-03 20:24 UTC, atiliosilfer commented
quando tentei rodar os testes do UserAppServiceImplTest deu erro 

"Underlying exception : org.mockito.exceptions.base.MockitoException: Could not modify all classes [class java.lang.Object, class puc.util.JwtUtil]
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class puc.util.JwtUtil."

![image](https://github.com/user-attachments/assets/b4d3e18c-fd14-4486-8b5d-97bf50a26227)

2024-09-03 20:49 UTC, atiliosilfer approved these changes
Rodando com o Java 17 aqui foi

2024-09-03 21:12 UTC, Lucas-Angelo approved these changes

2024-09-03 21:13 UTC, merged